//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> InstantPurchasePrice { get; set; }
        public Nullable<decimal> InstantSalePrice { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public Nullable<int> NumberOfProducts { get; set; }
        public Nullable<byte> RegistrationStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
